@startuml
struct GameConfig {
    + game_speed : float
    ...
}
GameConfig <-- Game

enum GameState {
    kMenu
    kMap
    kStory
    kPuzzle
}
GameState -- Game

struct StorySlide {
    + stop : bool
    + text : string
    + picture : string
}
note top
Picture is separate from text
because picture is centered in terminal
while text doesn't contain line breaks
and is wrapped
end note

class StoryReader {
    - vector<StorySlide> slides
    + loadStory(path)
    + advance() : bool
    + draw()
}

class Game {
    - puzzle : optional<Puzzle>
    - reader : StoryReader
    - progress : map<LevelID, bool>
    - selected_puzzle : LevelID
    - config : GameConfig
    - state : GameState
    - code : String
    - unlocked_spells : vector<CommandType>
    - hx_factor: int
    + processInputEvents()
    + draw()
}
Puzzle <- Game

struct Cell {
    + entity : Entity*
    + passable : bool
    + has_flowers : bool
}
Cell <- CellData

class CellData {
    - data : vector<Cell>
    - map_width : int
}
CellData <-- Puzzle
class Puzzle {
    - cell_data : CellData
    - enemies : vector<Enemy*>
    - player : Player*
    - sim_lock : bool
    - cmd_queue : queue<pair<Entity*, Command>>
    + getTileDetails()
    + getPlayerStatus()
    + getSimulationStatus()
    + processPlayerCommands(vector<Command>)
    + advance()
    + drawCells()
}

enum CommandType {
    kArrow
    kFireball
    ...
}

enum Parameter {
    kAX
    kBX
    kAH
    ...
}

struct Command {
    + type : CommandType
    + param_a : Parameter
    + param_b : Parameter
}
CommandType -- Command
Parameter -- Command

abstract class Entity {
    - ax : char
    - bx : char
    - hx : char
    - available_spells : vector<CommandType>
    + getHp()
    + getAvailableSpells()
    + receiveDmg()
    + exec(Command cmd)
}
Entity o- Cell

class Player
note top
Has no additional
symbols. Differs from
Enemy in abstract
method implementations
end note
Entity <|-- Player


class Enemy {
    - hp : int
    + evaluateAI(data : CellData) : vector<Command>
}
Entity <|-- Enemy

Game -> StoryReader
StoryReader -> StorySlide

@enduml
